# Generated by Django 5.1.2 on 2025-04-04 16:42

import users.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[users.validator.validate_iranian_phone_number], verbose_name='شماره موبایل'),
        ),
    ]
