# Generated by Django 5.1.2 on 2025-03-30 17:10

import django.core.validators
import django.db.models.deletion
import managements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='media',
        ),
        migrations.AddField(
            model_name='anime',
            name='folder_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='files',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='managements.episode'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=managements.models.manga_upload_path_banner_titleimg),
        ),
        migrations.AlterField(
            model_name='anime',
            name='imdb',
            field=models.FloatField(default=0, help_text='value 0 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to=managements.models.manga_upload_path_banner_titleimg),
        ),
        migrations.AlterField(
            model_name='files',
            name='media_en',
            field=models.FileField(blank=True, null=True, upload_to=managements.models.manga_upload_path_files),
        ),
        migrations.AlterField(
            model_name='files',
            name='media_fa',
            field=models.FileField(blank=True, null=True, upload_to=managements.models.manga_upload_path_files),
        ),
    ]
