# Generated by Django 5.1.2 on 2024-12-09 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_taglist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='imdb',
            field=models.IntegerField(default=0, help_text='value 1 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
