# Generated by Django 5.1.2 on 2024-10-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_episode_anime_episode_season_season_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='anime',
        ),
    ]
