# Generated by Django 5.1.2 on 2025-04-03 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_remove_episode_media_anime_folder_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.FloatField(default=0, help_text='value 0 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
