# Generated by Django 5.1.2 on 2024-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_remove_episode_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
