# Generated by Django 5.1.2 on 2024-12-09 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_alter_anime_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='imdb',
            field=models.FloatField(default=0, help_text='value 1 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.anime')),
            ],
        ),
    ]
