# Generated by Django 5.1.2 on 2024-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_anime_imdb_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
