# Generated by Django 5.1.2 on 2024-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_episode_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
