# Generated by Django 5.1.2 on 2024-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_anime_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='flag',
            field=models.BooleanField(),
        ),
    ]
