# Generated by Django 5.1.2 on 2024-12-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_post_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
