# Generated by Django 5.1.2 on 2024-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_alter_anime_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='flag',
        ),
    ]
