# Generated by Django 5.1.2 on 2024-12-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
    ]
