# Generated by Django 5.1.2 on 2024-12-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_remove_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lmodified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
