# Generated by Django 5.1.2 on 2024-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_remove_anime_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='click',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='imdb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
