# Generated by Django 5.1.2 on 2024-11-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0008_anime_click_anime_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
