# Generated by Django 5.1.2 on 2024-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0009_alter_anime_banner_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
