# Generated by Django 5.1.2 on 2025-01-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_menu_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
