# Generated by Django 5.1.2 on 2024-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_alter_anime_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_img',
            field=models.FileField(blank=True, null=True, upload_to='G:\\Programming\\django\\manga\\media'),
        ),
    ]
