# Generated by Django 5.1.2 on 2025-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_menu_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
