# Generated by Django 5.1.2 on 2024-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_alter_anime_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
