# Generated by Django 5.1.2 on 2025-01-24 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_alter_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.tag'),
        ),
    ]
