# Generated by Django 5.1.2 on 2024-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0013_alter_anime_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
