# Generated by Django 5.1.2 on 2025-02-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0014_remove_menu_title_menu_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantTextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='managements.menu'),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
