# Generated by Django 5.1.2 on 2024-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0014_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
