# Generated by Django 5.1.2 on 2025-03-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0015_wanttextbox_alter_menuoption_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttextbox',
            name='color',
        ),
    ]
