# Generated by Django 5.1.2 on 2024-11-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0015_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes_a', to='managements.anime'),
        ),
    ]
