# Generated by Django 5.1.2 on 2025-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0016_remove_wanttextbox_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='media',
            new_name='media_en',
        ),
        migrations.AddField(
            model_name='episode',
            name='media_fa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
