# Generated by Django 5.1.2 on 2025-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0017_rename_media_episode_media_en_episode_media_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_fa', models.FileField(blank=True, null=True, upload_to='')),
                ('media_en', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='media_en',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='media_fa',
        ),
    ]
