# Generated by Django 5.1.2 on 2024-11-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0017_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
