# Generated by Django 5.1.2 on 2025-03-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0018_files_remove_episode_media_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='managements.files'),
        ),
    ]
