# Generated by Django 5.1.2 on 2024-11-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0019_remove_banner_title_banner_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='managements.anime'),
        ),
    ]
